### ISSUE TITLE
Add method to retrieve process details object

### ISSUE THREAD

**Issue by MALATHI02** [OpenDataAlex/process_tracker_python#127]
Inputs to methods - process_id,source_object_name (all/one/null value(s) can be passed).

**Possible SQL** Below SQL statement has been run on Oracle SQL Developer UI
select p.process_id, process_name, so.source_id,source_name,source_object_id,source_object_name,process_type_name
  from process_tracker.source_object_lkup so, process_tracker.source_lkup sl, process_tracker.process_source ps, 
  process_tracker.process p,process_tracker.process_type_lkup ptl
    where  p.process_type_id = ptl.process_type_id
        and so.source_id = sl.source_id
        and so.source_id = ps.source_id
        and ps.process_id = p.process_id
        and p.process_id =  coalesce(&processid, p.process_id)
        and source_object_name = coalesce(&srcobjnm, source_object_name)

![image](https://user-images.githubusercontent.com/17622348/68885170-a216cc00-06e2-11ea-92d2-9d6fa554b362.png)

**Comment by OpenDataAlex** [comment]
Should not be searching for processes based on source object name, as discussed.
